services:
  php:
    build: .
    ports:
      - "8000:80"
      - "3000:3000"
    volumes:
      - ./laravel:/var/www/html:rw,cached
      - ./laravel/config/apache.conf:/etc/apache2/sites-available/000-default.conf
      - /var/www/html/node_modules 
      - /var/www/html/public/build
      - /var/www/html/vendor

    environment:
      - DB_HOST=db
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:latest  # Especifique a imagem do seu banco de dados
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'laravel'
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge


